# 데이터 구조 심화 (Advanced Data Structures)

**수업 시간**: 3시간  
**구성**: 강의 및 실습 2시간 + 퀴즈 1시간  
**수준**: 중급  
**선수 학습**: 변수, 데이터 타입, 연산자, 입출력, 조건문, 반복문, 리스트, 튜플, 딕셔너리

---

## 🎯 학습 목표

이 수업을 마친 후 학생들은 다음을 할 수 있습니다:

- 데이터 구성을 위한 중첩 리스트(nested list) 생성 및 사용하기
- 딕셔너리와 리스트를 효과적으로 조합하기
- 고유 컬렉션을 위한 세트(set) 자료형 사용하기
- 다양한 상황에 적합한 데이터 구조 선택하기

---

## 📊 1. 중첩 리스트 (Nested Lists)

### 중첩 리스트란?

**중첩 리스트(Nested List)**는 다른 리스트 안에 있는 리스트입니다. **상자 안의 상자**처럼 생각해보세요.

### 간단한 예시

In [ ]:
# 학생 성적 - 각 내부 리스트는 한 학생의 점수들
grades = [
    [85, 90, 78],    # 1번 학생
    [92, 88, 95],    # 2번 학생  
    [76, 82, 89]     # 3번 학생
]

# 요소 접근
first_student = grades[0]           # [85, 90, 78]
first_student_first_grade = grades[0][0]  # 85

print(f"1번 학생 성적: {first_student}")
print(f"1번 학생 첫 번째 성적: {first_student_first_grade}")

### 실용 예시: 주간 시간표

In [ ]:
# 주간 시간표 - 3일, 각 4교시
schedule = [
    ["수학", "국어", "과학", "미술"],      # 월요일
    ["과학", "수학", "체육", "음악"],      # 화요일
    ["국어", "미술", "수학", "사회"]       # 수요일
]

# 모든 수학 수업 찾기
print("수학 수업 시간표:")
days = ["월요일", "화요일", "수요일"]
for day_index, daily_classes in enumerate(schedule):
    for period_index, subject in enumerate(daily_classes):
        if subject == "수학":
            print(f"{days[day_index]} - {period_index + 1}교시")

### 2차원 리스트 작업

In [ ]:
# 간단한 성적 계산
test_scores = [
    [85, 90, 78],
    [92, 88, 95],
    [76, 82, 89]
]

# 각 학생의 평균 계산
print("학생별 평균:")
for i, scores in enumerate(test_scores):
    average = sum(scores) / len(scores)
    print(f"학생 {i+1}: {average:.1f}")

# 시험별 평균 계산
print("시험별 평균:")
for test_num in range(3):  # 3번의 시험
    total = 0
    for student_scores in test_scores:
        total += student_scores[test_num]
    average = total / len(test_scores)
    print(f"시험 {test_num+1}: {average:.1f}")

---

## 🔧 2. 딕셔너리 고급 활용

### 리스트를 포함한 딕셔너리

In [ ]:
# 여러 성적을 가진 학생
student = {
    "name": "김철수",
    "age": 20,
    "grades": [85, 90, 78, 92],
    "subjects": ["수학", "과학", "국어", "사회"]
}

# 복잡한 데이터 접근
name = student["name"]
first_grade = student["grades"][0]
math_subject = student["subjects"][0]

print(f"학생: {name}")
print(f"첫 번째 성적: {first_grade}")
print(f"수학 성적: {first_grade}")

### 딕셔너리의 리스트

In [ ]:
# 여러 학생들
students = [
    {"name": "김철수", "age": 20, "grade": 85},
    {"name": "이영희", "age": 19, "grade": 92},
    {"name": "박민수", "age": 21, "grade": 78}
]

# 높은 성적의 학생들 찾기
print("우수 학생 (성적 >= 85):")
for student in students:
    if student["grade"] >= 85:
        print(f"- {student['name']}: {student['grade']}")

# 평균 성적 계산
total = sum(student["grade"] for student in students)
average = total / len(students)
print(f"반 평균: {average:.1f}")

---

## 🔸 3. 세트 자료형 (Set Data Type)

### 세트란?

**세트(Set)**는 **중복이 없는** **고유한** 항목들의 모음입니다. **고유한 구슬들의 가방**처럼 생각해보세요.

### 세트 생성

In [ ]:
# 방법 1: 중괄호 사용
fruits = {"사과", "바나나", "오렌지", "사과"}  # 중복 제거됨
print(fruits)  # {'오렌지', '바나나', '사과'}

# 방법 2: 리스트로부터
numbers = set([1, 2, 3, 2, 1, 4])
print(numbers)  # {1, 2, 3, 4}

# 멤버십 확인
print("사과" in fruits)  # True
print("포도" in fruits)  # False

### 중복 제거

In [ ]:
# 리스트에서 중복 제거
numbers_with_duplicates = [1, 2, 2, 3, 3, 4]
unique_numbers = list(set(numbers_with_duplicates))
print(f"원본: {numbers_with_duplicates}")
print(f"중복 제거: {unique_numbers}")

# 고유 항목 개수 세기
text = "안녕하세요 안녕하세요"
words = text.split()
unique_words = set(words)
print(f"고유 단어: {unique_words}")
print(f"고유 단어 개수: {len(unique_words)}")

### 세트 연산

In [ ]:
# 다른 수업을 듣는 학생들
math_students = {"김철수", "이영희", "박민수"}
science_students = {"이영희", "박민수", "최지영"}

# 두 수업을 모두 듣는 학생들
both_classes = math_students & science_students
print(f"두 수업 모두 수강: {both_classes}")

# 모든 학생들
all_students = math_students | science_students
print(f"전체 학생: {all_students}")

# 수학만 듣는 학생들
only_math = math_students - science_students
print(f"수학만 수강: {only_math}")

---

## ⚖️ 4. 데이터 구조 선택

### 언제 무엇을 사용할까?

| 데이터 구조 | 언제 사용 | 예시 |
|-------------|-----------|------|
| **리스트** | 순서 필요, 변경 가능 | 쇼핑 카트 항목들 |
| **튜플** | 고정 데이터, 좌표 | (x, y) 위치 |
| **딕셔너리** | 키-값 검색 | 학번 → 이름 |
| **세트** | 고유 항목만 | 사용자 ID, 고유 태그 |

### 간단한 결정 가이드

In [ ]:
# 예시: 학생 관리

# 성적에는 리스트 사용 (순서가 있고, 변경 가능)
grades = [85, 90, 78]

# 생년월일에는 튜플 사용 (고정 정보)
birth_info = (2003, 5, 15)  # 년, 월, 일

# 조회에는 딕셔너리 사용
student_info = {"name": "김철수", "id": "S001"}

# 고유 과목에는 세트 사용
subjects = {"수학", "과학", "국어"}

print(f"성적: {grades}")
print(f"출생년도: {birth_info[0]}")
print(f"학생: {student_info['name']}")
print(f"과목: {subjects}")

---

## 🔄 5. 데이터 구조 조합

### 간단한 복합 예시

In [ ]:
# 복합 데이터 구조를 사용한 학교 시스템
school = {
    "name": "영남이공대학교",
    "students": [
        {
            "name": "김철수",
            "grades": [85, 90, 78],
            "subjects": {"수학", "과학", "국어"}
        },
        {
            "name": "이영희", 
            "grades": [92, 88, 95],
            "subjects": {"수학", "미술", "음악"}
        }
    ]
}

# 중첩된 데이터 접근
school_name = school["name"]
first_student = school["students"][0]
alice_first_grade = school["students"][0]["grades"][0]

print(f"학교: {school_name}")
print(f"첫 번째 학생: {first_student['name']}")
print(f"김철수의 첫 번째 성적: {alice_first_grade}")

# 수학을 듣는 학생들 찾기
print("수학을 수강하는 학생들:")
for student in school["students"]:
    if "수학" in student["subjects"]:
        print(f"- {student['name']}")

---

## 🔧 실습 문제

### 실습 1: 성적 관리 시스템

**문제**: 중첩 리스트를 사용하여 여러 시험에 대한 학생 점수를 저장하는 간단한 성적 관리 시스템을 만드세요.

**요구사항**:
- 3명 학생, 3개 시험 성적 저장
- 각 학생의 평균 계산
- 전체 최고 점수 찾기

**정답**:

In [ ]:
# 학생 성적: [학생1, 학생2, 학생3]
# 각 학생은 3번의 시험 점수를 가짐
grades = [
    [85, 90, 78],   # 학생 1
    [92, 88, 95],   # 학생 2
    [76, 82, 89]    # 학생 3
]

student_names = ["김철수", "이영희", "박민수"]

print("성적 관리 시스템")
print("=" * 20)

# 모든 성적 표시
print("전체 학생 성적:")
for i, student_grades in enumerate(grades):
    print(f"{student_names[i]}: {student_grades}")

# 학생 평균 계산
print("\n학생별 평균:")
for i, student_grades in enumerate(grades):
    average = sum(student_grades) / len(student_grades)
    print(f"{student_names[i]}: {average:.1f}")

# 최고 점수 찾기
highest_score = 0
best_student = ""
for i, student_grades in enumerate(grades):
    for score in student_grades:
        if score > highest_score:
            highest_score = score
            best_student = student_names[i]

print(f"\n최고 점수: {highest_score}점 ({best_student})")

# 시험별 평균 계산
print("\n시험별 평균:")
for test_num in range(3):
    total = 0
    for student_grades in grades:
        total += student_grades[test_num]
    average = total / len(grades)
    print(f"시험 {test_num + 1}: {average:.1f}")

### 실습 2: 학생 데이터베이스 시스템

**문제**: 딕셔너리의 리스트를 사용하여 학생 데이터베이스를 만드세요. 학생 정보를 저장하고 기본 연산을 수행하세요.

**요구사항**:
- 학생 이름, 나이, 성적 저장
- 나이별 학생 찾기
- 학급 통계 계산

**정답**:

In [ ]:
# 학생 데이터베이스
students = [
    {"name": "김철수", "age": 20, "grade": 85, "major": "소프트웨어융합과"},
    {"name": "이영희", "age": 19, "grade": 92, "major": "기계공학과"},
    {"name": "박민수", "age": 20, "grade": 78, "major": "전자공학과"},
    {"name": "최지영", "age": 21, "grade": 88, "major": "화학공학과"}
]

print("학생 데이터베이스 시스템")
print("=" * 25)

# 모든 학생 표시
print("전체 학생:")
for student in students:
    print(f"이름: {student['name']}, 나이: {student['age']}, 성적: {student['grade']}")

# 20세 학생 찾기
print("\n20세 학생:")
for student in students:
    if student["age"] == 20:
        print(f"- {student['name']} (성적: {student['grade']})")

# 학급 통계 계산
total_grade = sum(student["grade"] for student in students)
average_grade = total_grade / len(students)
highest_grade = max(student["grade"] for student in students)
lowest_grade = min(student["grade"] for student in students)

print(f"\n학급 통계:")
print(f"평균 성적: {average_grade:.1f}")
print(f"최고 성적: {highest_grade}")
print(f"최저 성적: {lowest_grade}")

# 전공별 학생 찾기
target_major = "소프트웨어융합과"
print(f"\n{target_major} 전공 학생:")
for student in students:
    if student["major"] == target_major:
        print(f"- {student['name']}")

# 나이별 분포
print(f"\n나이별 분포:")
ages = {}
for student in students:
    age = student["age"]
    ages[age] = ages.get(age, 0) + 1

for age, count in sorted(ages.items()):
    print(f"{age}세: {count}명")

### 실습 3: 고유 항목 관리자

**문제**: 세트를 사용하여 고유한 데이터 컬렉션을 관리하세요. 중복을 제거하고 세트 연산을 수행하세요.

**요구사항**:
- 리스트에서 중복 제거
- 공통 및 고유 요소 찾기
- 학생 수강 관리

**정답**:

In [ ]:
# 수강 신청 데이터
course_a_students = ["김철수", "이영희", "박민수", "최지영", "김철수", "이영희"]
course_b_students = ["이영희", "박민수", "정현우", "한미영", "박민수"]

print("고유 항목 관리자")
print("=" * 15)

# 세트를 사용하여 중복 제거
unique_course_a = set(course_a_students)
unique_course_b = set(course_b_students)

print("수강 신청 현황 (중복 제거):")
print(f"A과목: {unique_course_a}")
print(f"B과목: {unique_course_b}")

# 두 과목을 모두 듣는 학생들
both_courses = unique_course_a & unique_course_b
print(f"\n두 과목 모두 수강: {both_courses}")

# 모든 학생들
all_students = unique_course_a | unique_course_b
print(f"전체 학생: {all_students}")

# A과목만 듣는 학생들
only_course_a = unique_course_a - unique_course_b
print(f"A과목만 수강: {only_course_a}")

# B과목만 듣는 학생들
only_course_b = unique_course_b - unique_course_a
print(f"B과목만 수강: {only_course_b}")

# 통계
print(f"\n통계:")
print(f"총 고유 학생 수: {len(all_students)}")
print(f"A과목 수강생: {len(unique_course_a)}")
print(f"B과목 수강생: {len(unique_course_b)}")
print(f"두 과목 모두 수강: {len(both_courses)}")

# 특정 학생 수강 확인
check_student = "김철수"
if check_student in unique_course_a:
    print(f"\n{check_student}는 A과목을 수강합니다")
if check_student in unique_course_b:
    print(f"{check_student}는 B과목을 수강합니다")
if check_student not in unique_course_b:
    print(f"{check_student}는 B과목을 수강하지 않습니다")

---

## 📝 퀴즈

### 퀴즈 1: 세트 연산과 중복 제거
**문제**: 리스트 `[1, 2, 2, 3, 3, 3, 4]`가 주어졌을 때, 다음을 수행하는 코드를 작성하세요:

1. 세트를 사용해 중복을 제거하고 결과 출력
2. 두 세트 생성: `even_numbers = {2, 4, 6, 8}`과 위 리스트로부터 `given_numbers`
3. 두 세트에 모두 나타나는 숫자 찾기
4. even_numbers 세트에만 있는 숫자 찾기

### 퀴즈 2: 2차원 리스트 탐색
**문제**: 2차원 리스트 `matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]`가 주어졌을 때, 다음을 수행하는 코드를 작성하세요:

1. 가운데 값 (5) 출력
2. 첫 번째 열의 모든 값 출력
3. 행렬의 모든 숫자의 합 계산 및 출력
4. 행렬에서 가장 큰 숫자 찾기 및 출력

### 퀴즈 3: 학생 데이터 분석
**문제**: 학생 딕셔너리의 리스트가 있습니다. 데이터를 분석하는 코드를 작성하세요.

In [ ]:
students = [
    {"name": "김철수", "age": 19, "grade": 85},
    {"name": "이영희", "age": 20, "grade": 92},
    {"name": "박민수", "age": 20, "grade": 78},
    {"name": "최지영", "age": 19, "grade": 88}
]

다음을 수행하는 코드를 작성하세요:

1. 20세인 모든 학생 찾기
2. 모든 학생의 평균 성적 계산
3. 가장 높은 성적을 받은 학생 찾기
4. 19세인 학생 수 계산

---

## 📖 참고 자료

1. **파이썬 공식 문서 - 데이터 구조**: https://docs.python.org/ko/3/tutorial/datastructures.html
   - 리스트, 세트, 데이터 구조에 대한 공식 가이드

2. **점프 투 파이썬 - 집합**: https://wikidocs.net/1015
   - 한국어로 된 파이썬 세트 설명

3. **코딩 도장 - 2차원 리스트**: https://dojang.io/mod/page/view.php?id=2288
   - 2차원 리스트 작업의 실용적 예시

4. **Real Python - 파이썬 세트**: https://realpython.com/python-sets/
   - 영어 자료이지만 파이썬 세트에 대한 종합 튜토리얼

---

## 💡 성공을 위한 팁

### 모범 사례
- **간단하게 시작**: 조합하기 전에 기본 구조부터
- **고유성을 위해 세트 사용**: 고유한 항목이 필요할 때 세트가 완벽
- **구조 계획**: 데이터를 어떻게 사용할지 생각

### 피해야 할 일반적인 실수
- **과도한 중첩**: 구조를 너무 복잡하게 만들지 말 것
- **잘못된 데이터 타입**: 필요에 맞는 구조 선택
- **중복 망각**: 세트가 자동으로 중복을 제거한다는 것 기억

### 실제 활용 사례
- **학생 관리 시스템**: 성적, 출석, 수강 정보 통합 관리
- **재고 관리**: 상품 분류, 재고 추적, 주문 처리
- **데이터 분석**: 중복 제거, 그룹화, 통계 계산

---

## 📋 숙제

### 연습 문제

1. **전화번호부 시스템**: 딕셔너리 리스트를 사용한 간단한 전화번고부 만들기 (이름, 번호, 그룹별 관리)

2. **공통 친구 찾기**: 세트를 사용해 두 사람 간의 공통 친구와 각자만의 친구 찾기

3. **시험 성적 분석**: 중첩 리스트로 여러 과목, 여러 시험의 성적을 관리하고 다양한 통계 계산

4. **도서관 관리**: 책 정보(제목, 저자, 장르, 대출 상태)를 딕셔너리로 저장하고 리스트로 관리

### 도전 문제

5. **영남이공대학교 수강신청 시스템**: 
   - 과목별 수강생 관리 (세트 활용)
   - 학생별 시간표 관리 (중첩 구조)
   - 수강 충돌 검사
   - 수강 통계 분석

**프로그래밍 여정에 행운을 빕니다!**